### ISSUE TITLE
Random parameters

### ISSUE THREAD

**Issue by jmannseth** [colemonnahan/adnuts#10]
Hi,

I have been trying the sample_tmb function on an 'obj' that includes random parameters (I see in your example that you use "random = NULL"). I get the following warning message: 
####
In sample_tmb(obj = obj2, iter = 40, chains = 1, init = initran,  :
  Some parameters declated as random.  Are you sure? For MCMC this is usually turned off
####
It takes about 9h for me to finish the sampling (for only 40 iterations).

My question for now is if sample_tmb can be used with the random parameters?

PS: I can upload  an example if needed.

Thanks
Janne

**Comment by colemonnahan** [comment]
Hi @jmannseth, when you leave certain parameters set as "random" then TMB will do the Laplace approximation *at each iteration*. Keep in mind that each NUTS iteration can be hundreds of evaluations. So it makes sense that it would be so slow.

That is why I recommend turning it off when calling `MakeADFun`. Try running again that way. In the Bayesian framework you are integrating all parameters.

**Comment by colemonnahan** [comment]
Hi @jmannseth I reworked the package so that you can leave parameters as "random" but the MCMC code will ignore it by default. Thus you don't have to rebuild your model with `MakeADFun`. If you have a chance to try it again, install from the master branch and try your model again. I'd be curious to see how it works.

**Comment by jmannseth** [comment]
Hi!

Thank you @colemonnahan . I have tried it both ways now, and it is faster now that that you have reworked the package. It only takes round 3 hours instead of 9!

**Comment by colemonnahan** [comment]
Yikes. Does that seem reasonable? Is it a big model? What is the average treedepth? Is it converging?

**Comment by jmannseth** [comment]
Yes, the model is quite big. It is converging, and the average treedepth is 10.

**Comment by colemonnahan** [comment]
I suggest switching to tmbstan for this and all TMB models.
